config:
 hacluster:
  cluster_count:
   gte: 3
 ntp:
  auto_peers:
   eq: false
 nrpe:
  lacp_bonds:
   neq: ""
   suffixes: [host, physical]
  netlinks:
   neq: ""
   suffixes: [host, physical]
 landscape-client:
  disable-unattended-upgrades:
   eq: true

subordinates:
 telegraf:
  where: all except prometheus
  # and prometheus-ceph-exporter and prometheus-openstack-exporter
 landscape-client:
  where: all except landscape-server
 filebeat:
  where: all except graylog
 canonical-livepatch:
  where: host only
 nrpe:
  where: container aware
  host-suffixes: [host, physical, guest]
  container-suffixes: [lxd, container]
  exceptions: [nagios]
  allow-multiple: true  # There can be multiple nrpe units, see LP#1855858
 ntp:
  # You don't want NTP in a container dueling with ntp in the host
  where: host only
 thruk-agent:
  where: on nagios
 hw-health:
  where: metal only
 logrotated:
  where: all
 local-users:
  where: all or nothing

# openstack and k8s should check nrpe relations. See LP#1965762
relations base check: &relations-base-check
  # NOTE(gabrielcocenza) filebeat, telegraf, nrpe are necessary until switch to the COS
  - charm: nrpe
    check: [
      ["*:nrpe-external-master", "nrpe:nrpe-external-master"]
    ]
    # every machine has nrpe unit on it. See LP#1893272
    ubiquitous: true

  - charm: telegraf
    ubiquitous: true

  - charm: filebeat
    ubiquitous: true

  - charm: landscape-client
    ubiquitous: true

  - charm: ubuntu-advantage
    ubiquitous: true
