---
name: juju-lint
base: core18
summary: Linter for Juju models to compare deployments with configurable policy
adopt-info: juju-lint
description: |
    Linter for remote or local Juju models.
    Compares remote deployments with configurable policy rules.
    Linting can also be performed on a YAML file representing cloud state.
grade: stable
confinement: classic
apps:
  juju-lint:
    command: juju-lint
    environment:
      PATH: "/snap/juju-lint/current/bin:/snap/juju-lint/current/usr/bin:/bin:/usr/bin:"
      PYTHONPATH: $SNAP/usr/lib/python3.6/site-packages:$SNAP/usr/lib/python3.6/dist-packages:$PYTHONPATH
parts:
  juju-lint:
    plugin: python
    python-version: python3
    requirements:
      - requirements.txt
    source: .
    override-build: |
        snapcraftctl build
        echo "Version: $(python3 setup.py --version)"
        snapcraftctl set-version "$(python3 setup.py --version)"
  juju-lint-contrib:
    after:
      - juju-lint
    plugin: dump
    source: .
    prime:
      - contrib
