---
name: juju-lint
base: core18
version: git
summary: Linter for Juju models to compare deployments with configurable policy
description: |
    Linter for remote or local Juju models.
    Compares remote deployments with configurable policy rules.
    Linting can also be performed on a YAML file representing cloud state.
grade: stable
confinement: classic
apps:
  juju-lint:
    command: juju-lint
    plugs:
      - network
      - ssh-keys
parts:
  juju-lint:
    plugin: python
    python-version: python3
    source: .
  juju-lint-contrib:
    plugin: dump
    source: .
    prime:
      - contrib
