# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Full test suite

on:
  pull_request_review:
    types: [ submitted ]
  workflow_dispatch:
jobs:
  functional-tests:
    runs-on: ubuntu-latest
    name: Run functional tests
    steps:
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main  
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0        
      - name: install snapcraft
        run: sudo snap install snapcraft --classic
      - name: Run functional tests
        run: make functional